[default]
PROJECT_NAME = "API de Autos de Infração - IBAMA"

ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

CORS_ORIGIN = ["http://localhost:3000"]

REDIS_URL = "redis://redis:6379/0"

[development]
CORS_ORIGIN = ["*"]

[production]
ACCESS_TOKEN_EXPIRE_MINUTES = 15